sonar.projectKey=janrothen_e-paper
sonar.organization=janrothen

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=src/epaper/lib/**
